accounts/urls.py
from django.urls import path

from .views import signup, user_login,user_logout

app_name = 'accounts'

urlpatterns = [
    path('signup/',signup,name='signup'),
    path('login/',user_login,name='login'),
    path('logout/',user_logout,name='logout'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blogapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('admin/', admin.site.urls),
    path('new/', views.new, name = 'new'),
    path('community/', views.community, name = 'community'),
    path('mbtitest/', views.mbtitest, name = 'mbtitest'),
    path('detail/<int:post_id>', views.detail, name = 'detail'),
    path('edit/<int:post_id>', views.edit, name = 'edit'),
    path('delete/<int:post_id>', views.delete, name = 'delete'),
    path('edit_comment/<int:comment_id>', views.edit_comment, name = 'edit_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name = 'delete_comment'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('allauth.urls')),
   #path('main/', include('your_app.urls', namespace='your_app')),


]

blogapp/models.py
from django.db import models
from django.contrib.auth import get_user_model # 추가
# from django.contrib.auth.models import AbstractUser # user 커스텀하면 필요?




class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

User = get_user_model() # 사용자 모델 장고에서 만들어줌 -> 


# user 커스텀 방법도 있는데 일단 확장으로 진행?
'''class UserInfo(models.Model):
    mbti = models.CharField(verbose_name='MBTI',max_length=5)
    user = models.ForeignKey(to='User',on_delete=models.CASCADE)
   ''' 
 
        
# 커뮤니티 게시판 
class Post(models.Model):
    # 게시판: 제목, 내용, 작성일, 조회수, 작성자 ForeignKey, 그리고 뭐가 더 필요할까?
    
    # image = models.ImageField(verbose_name='이미지',null=True, blank=True) # 게시글 이미지 저장 필드  -- 이미지는 일단 보류
    
    headline = models.CharField(verbose_name='제목',max_length=200) # 제목
    content = models.TextField(verbose_name='내용') # 게시글 내용 저장 필드 
    created_at = models.DateTimeField(verbose_name='작성일',auto_now_add=True) # 작성 시간
    view_count = models.IntegerField(verbose_name='조회수',default=0)  # 조회수   
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE, null=True, blank=True) # 작성자
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)    
    def __str__(self):
        return self.headline
    # post의 이름을 post 제목으로 바꾸기 위해 변경
    

# 댓글 모델
class Comment(models.Model): # 일대다 구조
    
    # 댓글 : 댓글 내용, 작성일, 게시물 ForeignKey, 작성자 ForeignKey 
    
    content = models.TextField(verbose_name='내용')
    created_at =models.DateTimeField(verbose_name='작성일')
    post = models.ForeignKey(to = 'Post',on_delete=models.CASCADE)# CASCADE -> Post삭제되면 comment도 같이 삭제
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자랑 연결 ,사용자모델은 장고에서 만들어줌-> User = get_user_model() 
    is_secret = models.BooleanField(verbose_name='비밀글',default=False) # 비밀글인지
    is_anonymous = models.BooleanField(verbose_name='익명글',default=False) # 익명글인지
    def __str__(self):
        return self.content
    #comment의 이름을 comment 내용으로 바꾸기 위해 변경


class Refly(models.Model): # 일대다 구조
    
    # 댓글 : 댓글 내용, 작성일, 게시물 ForeignKey, 작성자 ForeignKey 
    
    content = models.TextField(verbose_name='내용')
    created_at =models.DateTimeField(verbose_name='작성일')
    post = models.ForeignKey(to = 'Post',on_delete=models.CASCADE)# CASCADE -> Post삭제되면 comment도 같이 삭제
    comment = models.ForeignKey(to = 'Comment',on_delete=models.CASCADE)# CASCADE -> Post삭제되면 comment도 같이 삭제
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자랑 연결 ,사용자모델은 장고에서 만들어줌-> User = get_user_model() 
    def __str__(self):
        return self.content
    #comment의 이름을 comment 내용으로 바꾸기 위해 변경

'''
모델 추가 및 수정 후 migration 필요

python manage.py makemigrations 실행
0002_post_comment.py 파일 생성됨
ex) ->  Migrations for 'blogapp':
            blogapp\migrations\0002_post_comment.py 
                - Create model Post
                - Create model Comment
그리고 
python manage.py migrate 실행
ex) ->  Operations to perform:
            Apply all migrations: admin, auth, blogapp, contenttypes, sessions
        Running migrations:
            Applying blogapp.0002_post_comment... OK

sqlite 설치해서 확인해보면 데이터 확인 가능
'''

blogapp/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone



from .models import Post,Comment
User = get_user_model()


def home(request):
    return render(request, 'index.html')

@login_required
def new(request):
    if request.method=='GET':
        return render(request, 'new.html')
    else:        
        title = request.POST.get('title')
        body = request.POST.get('body')
        writer = request.user
        Post.objects.create(
            headline = title,
            content = body,
            writer = writer,
        )
        return HttpResponseRedirect('/community')


def community(request):
    post_list = Post.objects.all()
    context = {"post_list":post_list}
    return render(request,'community.html',context)


@login_required
def mbtitest(request):
    if request.method=='POST':
        first = request.POST.get('first_question')
        second = request.POST.get('second_question')
        third = request.POST.get('third_question')
        fourth = request.POST.get('fourth_question')
        result=first+second+third+fourth
        print(result)
        request.user.mbti = result
        request.user.save()


        return HttpResponseRedirect('/')
    else:
        return render(request,'mbtitest.html')
#리다이렉션이란 웹 브라우저에서 요청한 url을 다른 url로 변경하여 새로운 페이지로 이동시키는 기능
# 웹 애플리케이션에서 리다이렉션을 사용하는 경우
# 1. 사용자가 요청한 페이지를 삭제한 경우
# 2. 사용자가 요청한 페이지의 URL이 변경된 경우
# 3. 사용자가 로그인 또는 로그아웃 등의 작업을 수행한 후, 
#    이전 페이지로 다시 이동시키기 위한 경우

# HttpResponseRedirect를 사용할 때, 인자로 전달하는 URL은 반드시 절대 경로여야 한다.
# 따라서, 'communty' 대신 '/communty'로 변경하여야
# 원하는 URL로 리다이렉션이 가능하다.

@login_required
def detail(request,post_id):
        post = get_object_or_404(Post, pk = post_id)
        if request.method=='GET':
            context = {"post":post,}
            return render(request,"detail.html",context)
        else:
            comment_text = request.POST.get('comment_text')


            is_secret=False
            secret_value = request.POST.get('secret')
            if secret_value:
                is_secret = secret_value == 'on'

            is_anonymous =False
            anonymous_value = request.POST.get('anonymous')
            if anonymous_value:
                is_anonymous = anonymous_value == 'on'

            created_at = timezone.now()
            Comment.objects.create(
            content = comment_text,
            writer = request.user,
            created_at = created_at,
            post = post,
            is_secret = is_secret,
            is_anonymous = is_anonymous
            )
            return HttpResponseRedirect(reverse("detail", args=(post_id,)))


@login_required
def edit(request,post_id):
    #post = Post.objects.get(id=post_id)
    post = get_object_or_404(Post, pk = post_id)
    if request.user != post.writer:
        return Http404('잘못된 접근입니다.')
    if request.method=='POST':
        headline = request.POST.get('headline')
        content = request.POST.get('content')
        post.content=content
        post.headline=headline
        post.save()
        return HttpResponseRedirect(reverse("detail", args=(post_id,)))
    else:    
        context = {'post':post,}
        return render(request,'edit.html',context)

@login_required    
def delete(request,post_id):
    post = get_object_or_404(Post, pk = post_id)
    if request.user != post.writer:
        return Http404('잘못된 접근입니다.')
    if request.method=='POST':
        post.delete()
        return HttpResponseRedirect('/community')
    else:    
        return render(request,'community.html')
    

@login_required
def edit_comment(request,comment_id):
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user != comment.writer:
        return Http404('잘못된 접근입니다.')
    if request.method=='POST':  
        content =request.POST.get('edited_comment')  
        comment.content = content
        comment.save()
        return HttpResponseRedirect(reverse("detail", args=(comment.post.id,)))
    else:    
        post = get_object_or_404(Post,pk=comment.post.id)
        context = {'post':post,}
        return render(request,'detail.html',context)

@login_required    
def delete_comment(request,comment_id):
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user != comment.writer:
        return Http404('잘못된 접근입니다.')
    if request.method=='POST':        
        comment.delete()
        return HttpResponseRedirect(reverse("detail", args=(comment.post.id,)))
    else:    
        post = get_object_or_404(Post,pk=comment.post.id)
        context = {'post':post,}
        return render(request,'detail.html',context)

blogapp/templates/community.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MBTI Community</title>
    <style>
        header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
    </style>
</head>
<body>
    <header>
        <div style="text-align: center; font-weight: bold;">
            <a href="{% url 'home' %}">MBTI</a>
        </div>
    </header>
    {% if request.user %}
        <p> 나의 닉네임 : 
            {% if request.user.mbti %}
                {{ request.user.mbti }}인 
            {% endif %}
            {{ request.user }}
            {% if request.user.is_staff %}
            (관리자)
            {% endif %}
        </p>
        
    {% else %}
        <p> 회원가입을 해주세요! </p>
    {% endif %}

    <a href="{% url 'new' %}">글 작성하기</a>

    {% if post_list %}
    <ul>
    {% for post in post_list %}
        <li><a href="{% url 'detail' post.id %}">{{ post.headline }}</a>
        <br> 작성자 : {{ post.writer }} | MBTI : {{ post.writer.mbti }}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>글 목록이 없습니다.</p>
{% endif %}
</body>
</html>

blogapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
    <style>
        header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
        .btn{
            display: inline-block;

        }
        #hidden_form{
            display: block;
        }
        
    </style>
    
</head>
<body>
    <header>
        <div style="text-align: center; font-weight: bold;">
            <a href="{% url 'home' %}">MBTI</a>
        </div>
    </header>
    <div>
        <table border="1" style="border-collapse: collapse; width: 80%;">
            <tr>
                <td>
                    <p> 제목 </p>
                </td>
                <td>
                    <p>{{ post.headline }}</p>
                </td>
            </tr>
            <tr>
                <td> 작성자 </td>
                <td>
                    {{ post.writer }}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    MBTI : 
                    {% if post.writer.mbti %}
                        {{ post.writer.mbti }}
                    {% else %}
                        NONE
                    {% endif %}
                </td>
            </tr>
            <tr style="min-height: 500px;">
                <td>
                    <p> 내용   </p>
                </td>
                <td>
                    <p>{{ post.content }}</p>
                </td>
            </tr>
        </table>
        
        {% if request.user == post.writer %}
            <a href="{% url 'edit' post.id %}">수정하기</a>
            <form action="{% url 'delete' post.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="삭제하기">
            </form>
        {% endif %}
        <br><br><br>
        <table  border="1" style="border-collapse: collapse; width: 80%;">
            <tr>
                <td>
                    댓글 작성
                </td>
                <td>
                    <form action="{% url 'detail' post.id %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="comment_text">
                        <input type="submit" value="작성">
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        비밀 글 : <input type="checkbox" name="secret">
                        익명 글 : <input type="checkbox" name="anonymous">
                    </form>
                </td>
            </tr>
            {% for comment in post.comment_set.all %}
    <tr>
        <td>
            {% if comment.is_anonymous %}
                익명의 작성자
            {% else %}
                작성자 : {{ comment.writer }}
            {% endif %}
            
            <br>MBTI : 
            {% if comment.writer.mbti %}
                {{ comment.writer.mbti }}
            {% else %}
                NONE
            {% endif %}
            <br>
            {% if comment.is_secret %}
                (비밀글)
            {% endif %}
        </td> 
        <td>
            {% if comment.is_secret%}
                {% if request.user == comment.writer or request.user.is_staff%}
                    <p name="comment_text">{{ comment.content }}</p>
                {% endif %}
            {% else %}
                <p name="comment_text">{{ comment.content }}</p>
            {% endif %}
            {% if request.user == comment.writer %}
            <div> 
                <input type="button" value="누르면 hidden_form이 나오는 버튼" name="edit_button">
                <div name="hidden_form" id="hidden_form">
                    <form action="{% url 'edit_comment' comment.id %}" method="post" class="btn">
                        {% csrf_token %}
                        <input type="text" name="edited_comment" value="{{ comment.content }}">
                        <input type="submit" value="수정">
                    </form> 
                </div>
                
                <form action="{% url 'delete_comment' comment.id %}" method="post" class="btn">
                    {% csrf_token %}
                    <input type="submit" value="삭제">
                </form> 
            </div>
            {% endif %}
        </td>
    </tr>
{% endfor %}
            
        </table>
    </div>

</body>
</html>

blogapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit</title>
    <style>
        header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
    </style>
    
</head>
<body>
    <header>
        <div style="text-align: center; font-weight: bold;">
            <a href="{% url 'home' %}">MBTI</a>
        </div>
    </header>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <table border="1" style="border-collapse: collapse; width: 80%;">
                <tr>
                    <td>
                        <p> 제목 </p>
                    </td>
                    <td>
                        <p> <input type="text" value="{{ post.headline }}" name="headline"> </p>
                    </td>
                </tr>

                <tr style="min-height: 500px;">
                    <td>
                        <p> 내용   </p>
                    </td>
                    <td>
                        <p> <textarea name="content" cols="30" rows="10">{{ post.content }}</textarea> </p>
                            
                    </td>
                </tr>
            </table>
            <input type="submit" value="제출">
        </form>
</body>
</html>

blogapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
    <style>
        body{
            text-align: center;
        }
        header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
        nav{
            display: fixed;
        }
        .wrapper{
            background-color: rgb(217, 198, 120);
            height: 50px;
            display: flex;
            align-items: center;
            justify-content: left;
            
        }
        .right{
            margin-left: auto;
            margin-right: 20px;

        }
        .block{
            display: inline;
            margin-left: 20px;

        }
        .block a{
            text-decoration: none;
            font-size: 20px;
            color: white;
            font-weight: bold;
        }

    </style>
</head>
<body>
    <header>
        <div style="margin-bottom: 30px;">
            <a href="{% url 'home' %}">MY MBTI HOME</a>
        </div>
    </header>
    <nav>
        <div class="wrapper">
            <div class="left">
                <div class="block">
                    <a href="{% url 'community' %}">글 목록</a>
                </div>
                <div class="block">
                    <a href = "{% url 'new' %}">글 작성</a>
                </div>
            </div>
            <div class="right">
                
                {% if request.user.is_authenticated %}
                    <div class="block">
                        <a href="{% url 'mbtitest' %}"> MBTI TEST </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'accounts:logout' %}"> 로그아웃 </a>
                    </div>
                {% else %}
                    <div class="block">
                        <a href="{% url 'accounts:login' %}"> 로그인 </a>
                    </div>
                {% endif %}

            </div>
            
        </div>
        
    </nav>



        <!-- name을 이용해 하드코딩 하지 않고 url을 작성한 것  -->
</body>
</html>

blogapp/templates/mbtitest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MBTI TEST</title>
    <style>
        header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
        form{
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <div style="text-align: center; font-weight: bold;">
            <a href="{% url 'home' %}">MBTI</a>
        </div>
    </header>
    
     <br>
    <fieldset>
        <legend style="text-align: center;">MBTI TEST</legend>
        <form action="{% url 'mbtitest' %}" method="post">
            {% csrf_token %}
            1. 나는 혼자 있는 시간을 좋아한다. <br>
            YES : <input type="radio" name="first_question" value="I" required> &nbsp;&nbsp;&nbsp;&nbsp;
            NO : <input type="radio" name="first_question" value="E"> <br><br>
            2. 나는 혼자 있는 시간에 재미있는 상상을 주로 하곤 한다. <br>
            YES : <input type="radio" name="second_question" value="N" required>&nbsp;&nbsp;&nbsp;&nbsp;
            NO : <input type="radio" name="second_question" value="S"> <br><br>
            3. 나는 영화를 보면서 눈물을 흘린 적이 있다. <br>
            YES : <input type="radio" name="third_question" value="F" required> &nbsp;&nbsp;&nbsp;&nbsp;
            NO : <input type="radio" name="third_question" value="T"> <br><br>
            4. 현재 나의 책상은 정리되어 있다. <br>
            YES : <input type="radio" name="fourth_question" value="J" required> &nbsp;&nbsp;&nbsp;&nbsp;
            NO : <input type="radio" name="fourth_question" value="P"> <br><br>
            <input type="submit" value="제출">
        </form>
    </fieldset>
   
</body>
</html>

blogapp/templates/new.html
<style>
    header{
            text-align: center;
        }
        header a{
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 30px;
        }
        .posttext_field{
            text-align: center;
            display: flex;
            justify-content: center;
        }
        fieldset{
            width: 70%;
            display: flex;
            justify-content: center;
        }
</style>
<header>
    <div style="text-align: center; font-weight: bold;">
        <a href="{% url 'home' %}">MBTI</a>
    </div>
</header>
<div class="posttext_field">
    <fieldset>
        <legend style="text-align: center;">글 작성</legend>
        <form action = "{% url 'new'%}" method = "POST">
            {% csrf_token %}
            <div>

                <label for = "title">제목</label><br>
                <input type = "text" name = "title" id = "title" required>
                <br><br>
            </div>
            <div>
                <label for = "body">본문</label><br>
                <textarea name = "body" id = "body" cols = "30" rows = "10" required></textarea>
                <br><br>
            </div>
            <input type="submit" value = "글 작성">
            <br>
        </form>
    </fieldset>
</div>